# This rule is not used by the project gigapi-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the gigapi.gigapi.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gigapi-operator
    app.kubernetes.io/managed-by: kustomize
  name: gigapi-editor-role
rules:
- apiGroups:
  - gigapi.gigapi.io
  resources:
  - gigapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gigapi.gigapi.io
  resources:
  - gigapis/status
  verbs:
  - get
